# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: rouge
paginate: 10 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : http://hanqingguo.github.io


title : Hanqing Guo



author:
  name: Hanqingguo
  role: Jekyll Theme
  email: hguo@bsu.edu
  github: meliodus
  twitter: talk2ankan
  facebook: talk2ankan
  googleplus: +AnkanBiswasWorkspace
  bio: "Welcome to my personal page, I am a second year graduate student in Department of Computer Science, Intelligent communication Lab "
  uno-dbyll: https://raw.githubusercontent.com/meliodus/uno-dbyll/gh-pages/uno-dbyll.png
